# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ctm < Formula
  desc "Terminal-first browser workspace manager"
  homepage "https://github.com/liangquanzhou/chrome-tab-manager"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/liangquanzhou/chrome-tab-manager/releases/download/v1.0.0/ctm_1.0.0_darwin_amd64.tar.gz"
      sha256 "985c6bf1c072ea1fb76977a8689d225eecafb041e66b0fbeaaf5789456d2c8b0"

      define_method(:install) do
        bin.install "ctm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/liangquanzhou/chrome-tab-manager/releases/download/v1.0.0/ctm_1.0.0_darwin_arm64.tar.gz"
      sha256 "d195347f4028dcb2da8fd005ed6eb61539538e35f1881a567ce14d64638ee183"

      define_method(:install) do
        bin.install "ctm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/liangquanzhou/chrome-tab-manager/releases/download/v1.0.0/ctm_1.0.0_linux_amd64.tar.gz"
      sha256 "f5c86ae96e97e249b589eb1f1018334227de33b6b548bad15e92091bd0105beb"
      define_method(:install) do
        bin.install "ctm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/liangquanzhou/chrome-tab-manager/releases/download/v1.0.0/ctm_1.0.0_linux_arm64.tar.gz"
      sha256 "288e6c9c2cfdb43978faba4b3312f39b6919181aedbfbfdaa59f72c05cc2ddf3"
      define_method(:install) do
        bin.install "ctm"
      end
    end
  end

  test do
    system "#{bin}/ctm", "version"
  end
end
