# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentctl" do
  name "agentctl"
  desc "Multi-agent control plane CLI"
  homepage "https://github.com/liangquanzhou/agentctl"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentctl"

  on_macos do
    on_intel do
      url "https://github.com/liangquanzhou/agentctl/releases/download/v#{version}/agentctl_#{version}_darwin_amd64.tar.gz"
      sha256 "fdb77953ff5dd7ce330f7ac896087950557c99b4c90c575280f85a4f6da60fae"
    end
    on_arm do
      url "https://github.com/liangquanzhou/agentctl/releases/download/v#{version}/agentctl_#{version}_darwin_arm64.tar.gz"
      sha256 "090dabb8d276e567b7f74a28fa661a0c1202743b843d6f9d7de3c5519fdfb116"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/liangquanzhou/agentctl/releases/download/v#{version}/agentctl_#{version}_linux_amd64.tar.gz"
      sha256 "a44e45bae67eb3ba33f862c095b25b542150d1ff1814d0f1a710fb53639dc7bc"
    end
    on_arm do
      url "https://github.com/liangquanzhou/agentctl/releases/download/v#{version}/agentctl_#{version}_linux_arm64.tar.gz"
      sha256 "bca168ceea5d9187cf07f90b2b1ed4d68832364dd23e905376236f7434690ba2"
    end
  end

  caveats do
    "Run 'agentctl doctor' to verify your setup."
  end

  # No zap stanza required
end
