# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentctl < Formula
  desc "Multi-agent control plane CLI"
  homepage "https://github.com/liangquanzhou/agentctl"
  version "0.3.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/liangquanzhou/agentctl/releases/download/v0.3.6/agentctl_0.3.6_darwin_amd64.tar.gz"
      sha256 "f61273f529e393b21d7e7a6f15cab9cdbe425a8778190bba2872931a4068eea2"

      define_method(:install) do
        bin.install "agentctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/liangquanzhou/agentctl/releases/download/v0.3.6/agentctl_0.3.6_darwin_arm64.tar.gz"
      sha256 "31cee025c6ed0f5247a6bc5d1f5edcbb52623fd80f82aee93fdabbb2a2dc63de"

      define_method(:install) do
        bin.install "agentctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/liangquanzhou/agentctl/releases/download/v0.3.6/agentctl_0.3.6_linux_amd64.tar.gz"
      sha256 "9ee602d16c69df9c76becd686a5446e5c6642d99648842449582beadb04d5266"
      define_method(:install) do
        bin.install "agentctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/liangquanzhou/agentctl/releases/download/v0.3.6/agentctl_0.3.6_linux_arm64.tar.gz"
      sha256 "15b828be6e6c03c0f3a30f823d1401c462f15534bc310534fd4251896e1dec47"
      define_method(:install) do
        bin.install "agentctl"
      end
    end
  end

  test do
    system "#{bin}/agentctl", "--version"
  end
end
