# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentctl < Formula
  desc "Multi-agent control plane CLI"
  homepage "https://github.com/liangquanzhou/agentctl"
  version "0.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/liangquanzhou/agentctl/releases/download/v0.5.2/agentctl_0.5.2_darwin_amd64.tar.gz"
      sha256 "c314c7634c29d0aa7c58c1b5f94716b9632646525597bc1e30abd7d4879b429a"

      define_method(:install) do
        bin.install "agentctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/liangquanzhou/agentctl/releases/download/v0.5.2/agentctl_0.5.2_darwin_arm64.tar.gz"
      sha256 "9b3325c57de501d41e08d06635ce54703b3bf10a3c905900685b394f14094a42"

      define_method(:install) do
        bin.install "agentctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/liangquanzhou/agentctl/releases/download/v0.5.2/agentctl_0.5.2_linux_amd64.tar.gz"
      sha256 "9794f74cc10cbb526bd439fe52f5ce7799367b76445ebce7d9754cc9e2b35a6f"
      define_method(:install) do
        bin.install "agentctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/liangquanzhou/agentctl/releases/download/v0.5.2/agentctl_0.5.2_linux_arm64.tar.gz"
      sha256 "ac054ce8d26e1841d015e4a1bb9b59ad8f0b95217b2f93285c68b2e388692c61"
      define_method(:install) do
        bin.install "agentctl"
      end
    end
  end

  test do
    system "#{bin}/agentctl", "--version"
  end
end
